# Generated by Django 2.2.5 on 2019-10-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('created_at', models.DateTimeField()),
                ('primary_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
