# Generated by Django 2.2.5 on 2019-10-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbotcontrol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='primary_id',
        ),
        migrations.AddField(
            model_name='testmodel',
            name='id',
            field=models.AutoField(auto_created=True, default=42, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
