# Generated by Django 2.2.5 on 2019-10-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbotcontrol', '0002_auto_20191001_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
    ]
