# Generated by Django 2.2.6 on 2019-11-02 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discordbotcontrol', '0004_auto_20191101_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discordbotcontrol.Category', to_field='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
